SELECT *
FROM SalesLT.sqlpro_Product;

-------WHERE_____
---Find all products that are black.

SELECT *
FROM SalesLT.sqlpro_Product
WHERE Color = 'Black';

______ORDER BY______
---Find all products and show them from the most expensive to the least expensive.

SELECT *
FROM SalesLT.sqlpro_Product
ORDER BY ListPrice DESC;

_____ORDER BY_____
----Find all products and show them from the cheapest to the most expensive.

SELECT *
FROM SalesLT.sqlpro_Product
ORDER BY ListPrice ASC;

______OR______
----Find products that are Black OR Red.

SELECT *
FROM SalesLT.sqlpro_Product
WHERE Color = 'Black'
   OR Color = 'Red';
   
_____ AND_____
---Find all products that are black AND cost more than $500.

SELECT *
FROM SalesLT.sqlpro_Product
WHERE Color = 'Black'
AND ListPrice > 700;   

____AS(ALIAS)____
-----Show product names and rename ListPrice to Price.

SELECT
    Name AS ProductName,
    ListPrice AS Price
FROM SalesLT.sqlpro_Product;

  
_____BETWEEN____
---- Find products that cost between $500 and $1,000.  
SELECT *
FROM SalesLT.sqlpro_Product
WHERE ListPrice BETWEEN 500 AND 1000;

______IN_____
-----Find products that are Black, Red, or Blue.

SELECT *
FROM SalesLT.sqlpro_Product
WHERE Color IN ('Black', 'Red', 'Blue');


____LIKE____
----Find all products whose name starts with “Mountain”.
SELECT *
FROM SalesLT.sqlpro_Product
WHERE Name LIKE 'Mountain%';
   

_____DISTINCT_______
----Find all the different colors available in the Product table without showing duplicates.

SELECT DISTINCT Color
FROM SalesLT.sqlpro_Product;

____IS NULL____
----Find all products that do not have a color specified.

SELECT *
FROM SalesLT.sqlpro_Product
WHERE Color IS NULL;

_____COUNT____
------Find the total number of products in the Product table.

SELECT COUNT(*) AS TotalProducts
FROM SalesLT.sqlpro_Product;


____AVG____
-----Find the average price of all products.

SELECT AVG(ListPrice) AS AveragePrice
FROM SalesLT.sqlpro_Product;

_____GROUP BY_________
-----Find the number of products for each color.

SELECT Color, COUNT(*) AS ProductCount
FROM SalesLT.sqlpro_Product
GROUP BY Color;

_____HAVING_______
----Find colors that have more than 10 products.

SELECT Color, COUNT(*) AS ProductCount
FROM SalesLT.sqlpro_Product
GROUP BY Color
HAVING COUNT(*) > 10;

______SUM______
-----Find the total value of all products based on their list prices.

SELECT SUM(ListPrice) AS TotalListPrice
FROM SalesLT.sqlpro_Product;

______INNER JOIN_____
------Show each product name together with its product category name.

SELECT
    p.Name AS ProductName,
    pc.Name AS CategoryName
FROM SalesLT.sqlpro_Product AS p
INNER JOIN SalesLT.sqlpro_ProductCategory AS pc
    ON p.ProductCategoryID = pc.ProductCategoryID;
    
______JOIN + SUM + GROUP BY_____
----Find the total sales revenue generated by each product.

SELECT
    p.Name AS ProductName,
    SUM(sod.LineTotal) AS TotalRevenue
FROM SalesLT.sqlpro_SalesOrderDetail AS sod
INNER JOIN SalesLT.sqlpro_Product AS p
    ON sod.ProductID = p.ProductID
GROUP BY p.Name
ORDER BY TotalRevenue DESC;


______MAX & MIN______
-----Find the most expensive and least expensive product prices.

SELECT
    MAX(ListPrice) AS HighestPrice,
    MIN(ListPrice) AS LowestPrice
FROM SalesLT.sqlpro_Product;


_____TOP 5 PRODUCTS BY REVENUE_____
---Find the top 5 products that generated the most sales revenue.

SELECT TOP 5
    p.Name AS ProductName,
    SUM(sod.LineTotal) AS TotalRevenue
FROM SalesLT.sqlpro_SalesOrderDetail AS sod
INNER JOIN SalesLT.sqlpro_Product AS p
    ON sod.ProductID = p.ProductID
GROUP BY p.Name
ORDER BY TotalRevenue DESC;


_____RANK() Window Function______
-----Rank products from highest to lowest based on total sales revenue.

WITH ProductRevenue AS (
    SELECT
        p.Name AS ProductName,
        SUM(sod.LineTotal) AS TotalRevenue
    FROM SalesLT.sqlpro_SalesOrderDetail AS sod
    INNER JOIN SalesLT.sqlpro_Product AS p
        ON sod.ProductID = p.ProductID
    GROUP BY p.Name
)

SELECT
    ProductName,
    TotalRevenue,
    RANK() OVER (ORDER BY TotalRevenue DESC) AS RevenueRank
FROM ProductRevenue;


______MULTIPLE JOINS____
----Show each customer together with their sales orders and the total amount of each order.

SELECT
    c.FirstName,
    c.LastName,
    soh.SalesOrderID,
    soh.TotalDue
FROM SalesLT.sqlpro_Customer AS c
INNER JOIN SalesLT.sqlpro_SalesOrderHeader AS soh
    ON c.CustomerID = soh.CustomerID
ORDER BY soh.TotalDue DESC;

----Find which product categories generated the most sales revenue

SELECT
    pc.Name AS CategoryName,
    SUM(sod.LineTotal) AS TotalRevenue
FROM SalesLT.sqlpro_SalesOrderDetail AS sod
INNER JOIN SalesLT.sqlpro_Product AS p
    ON sod.ProductID = p.ProductID
INNER JOIN SalesLT.sqlpro_ProductCategory AS pc
    ON p.ProductCategoryID = pc.ProductCategoryID
GROUP BY pc.Name
ORDER BY TotalRevenue DESC;



- ==========================================
-- PROJECT CONCLUSION
-- ==========================================

/*
In this project, I used SQL to explore and analyze product,
customer, and sales data.

I filtered and sorted data, calculated product prices and sales
revenue, grouped products by different categories, and connected
multiple tables using JOINs.

I also analyzed customer orders, identified top-selling products,
and compared sales performance across product categories.

This project helped me practice SQL and understand how SQL can be
used to answer business questions using real-world sales data.
*/